"""
Django settings for vanoce project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/
https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators
https://docs.djangoproject.com/en/2.1/topics/i18n/
https://docs.djangoproject.com/en/2.1/howto/static-files/
"""
import os
import sys
from azure.keyvault import KeyVaultClient, KeyVaultAuthentication
from azure.common.credentials import ServicePrincipalCredentials
from msrestazure.azure_active_directory import MSIAuthentication

credentials = MSIAuthentication(resource='https://vault.azure.net')
client = KeyVaultClient(credentials)

#later sometimes
#DEBUG = False

SECRET_KEY = client.get_secret("https://b40.vault.azure.net/", "SECRET-KEY", "98d11c2fddcd400c985e1ba61fa030bb").value

DATABASES = {
   'default': {
	   'ENGINE': 'django.db.backends.postgresql_psycopg2',
	   'NAME': client.get_secret("https://b40.vault.azure.net/", "DATABASE-NAME", "4cda1508f1734f9eb17dff2f714d1c9f").value,
	   'USER': client.get_secret("https://b40.vault.azure.net/", "DATABASE-USER", "231fafb2d77044a7b40966409f374f9e").value,
	   'PASSWORD': client.get_secret("https://b40.vault.azure.net/", "DATABASE-PASSWORD", "b1af67888f91461fabe6e893875709ca").value,
	   'HOST': client.get_secret("https://b40.vault.azure.net/", "DATABASE-HOST", "4c6a2e23959349a6a8021387957efcdc").value,
	   'PORT': '5432',
 	}
}
