"""
Django settings for vanoce project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/
https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators
https://docs.djangoproject.com/en/2.1/topics/i18n/
https://docs.djangoproject.com/en/2.1/howto/static-files/
"""
import os
import sys
from azure.keyvault import KeyVaultClient, KeyVaultAuthentication
from azure.common.credentials import ServicePrincipalCredentials

credentials = None
"""
Create a function that prepares to retrieve secret key value/other credentials
"""
def auth_callback(server, resource, scope):
    credentials = ServicePrincipalCredentials(
        client_id = 'fffff2a3-935f-448c-9e4b-d0bdfb76deda', #client id
        secret = 'g]>={|y;O-=Q7e%4>WK./Q96]',
        tenant = '0f510a1b-c5e3-4209-8b58-1312c3193849',
        resource = "https://vault.azure.net"
    )
    token = credentials.token
    return token['token_type'], token['access_token']

client = KeyVaultClient(KeyVaultAuthentication(auth_callback))


#later sometimes
#DEBUG = False

SECRET_KEY = client.get_secret("https://b40.vault.azure.net/", "SECRET-KEY", "98d11c2fddcd400c985e1ba61fa030bb").value

DATABASES = {
   'default': {
	   'ENGINE': 'django.db.backends.postgresql_psycopg2',
	   'NAME': client.get_secret("https://b40.vault.azure.net/", "DATABASE-NAME", "76f97796b24a4833a467a2bb1ce64780").value,
	   'USER': client.get_secret("https://b40.vault.azure.net/", "DATABASE-USER", "6f6c1f6668ae45c0b85c54c1526d8d45").value,
	   'PASSWORD': client.get_secret("https://b40.vault.azure.net/", "DATABASE-PASSWORD", "34b5500d04f84f28ba64772d81aa4cb2").value,
	   'HOST': client.get_secret("https://b40.vault.azure.net/", "DATABASE-HOST", "4c6a2e23959349a6a8021387957efcdc").value,
	   'PORT': '5432',
 	}
}
