#Traefik version 1.7
# static configuration, you need to use appropriate docker compose file

debug = true
logLevel = "INFO"
InsecureSkipVerify = true

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
			[entryPoints.http.redirect]
			entryPoint = "https"

    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
      ]

    [entryPoints.traefik]
    address = ":9116"

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "melive.xyz"
watch = true
exposedByDefault = true

[acme]
email = "cincenko@outlook.com"
storage = "acme/certs.json"
entryPoint = "https"
resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
caServer = "https://acme-v02.api.letsencrypt.org/directory"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
onHostRule = true
  [acme.dnsChallenge]
  provider = "ovh"
  delayBeforeCheck = 10

[[acme.domains]]
  main = "*.melive.xyz"
