# Traefik version 2

[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[serversTransport]
  insecureSkipVerify = true
  maxIdleConnsPerHost = 0

[entryPoints.http]
  address = ":80"

[entryPoints.https]
  address = ":443"

[entryPoints.others]
  address = ":9116"


[http]
  [http.routers]
    [http.routers.traefik]
      entryPoints = ["http"]
      rule = "Host(`monitor.melive.xyz`, `www.monitor.melive.xyz`)"
      service = "traefik"
      middlewares = ["httpsredirect"]

    # [http.routers.traefik2]
    #   entryPoints = ["https"]
    #   rule = "Host(`monitor.melive.xyz`, `www.monitor.melive.xyz`)"
    #   service = "traefik"
    #   [http.routers.traefik2.tls]
    #     certResolver = "default"

[http.services]
    [http.services.traefik]
        [http.services.traefik.loadBalancer]
        [[http.services.traefik.loadBalancer.servers]]
            port = "http://localhost:9116"

[http.middlewares]
  [http.middlewares.httpsredirect.redirectScheme]
    scheme = "https"
    permanent = true

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS13"
    cipherSuites = [
        "TLS13-CHACHA20-POLY1305-SHA256",
        "TLS13-AES-256-GCM-SHA384",
        "TLS13-AES-128-GCM-SHA256"
    ]

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = "cincenko@outlook.com"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      storage = "acme/certs.json"
      [certificatesResolvers.default.acme.dnsChallenge]
        provider = "ovh"
        delayBeforeCheck = "10s"
        resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = true
    swarmMode = false

[api]
  insecure = true
  dashboard = true
  debug = true

[log]
  level = "INFO"

