# Traefik version 2

[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[serversTransport]
  insecureSkipVerify = true
  maxIdleConnsPerHost = 0

# [http]
#   [http.routers]
#     [http.routers.dashboard]
#       entryPoints = ["web"]
#       service = "monitor"
#       rule = "Path(`/foo`)"

#     [http.services]
#       [http.services.monitor]
#         [http.services.monitor.loadBalancer]
#           [[http.services.monitor.loadBalancer.servers]]
#             url = "http://foo/"

[entryPoints.web]
  address = ":80"

[entryPoints.web-secure]
  address = ":443"

[entryPoints.others]
  address = ":7070"

# [tls.options]
#   [tls.options.default]
#     minVersion = "VersionTLS12"
#     cipherSuites = [
#         "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
#         "TLS_RSA_WITH_AES_256_GCM_SHA384"
#     ]

# [certificatesResolvers]
#   [certificatesResolvers.default]
#     [certificatesResolvers.default.acme]
#       email = "cincenko@outlook.com"
#       storage = "acme/certs.json"
#       [certificatesResolvers.default.acme.dnsChallenge]
#         provider = "ovh"
#         delayBeforeCheck = "10s"
#         resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = true
    swarmMode = false
    # network = "traefik_proxy"
    # useBindPortIP = true

[api]
  insecure = true
  dashboard = true
  debug = true

[log]
  level = "INFO"

