# Traefik version 2
# static settingss
[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[serversTransport]
  insecureSkipVerify = true
  maxIdleConnsPerHost = 7

[entryPoints.web]
  address = ":80"

[entryPoints.web-secure]
  address = ":443"

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    curvePreferences = ["CurveP521", "CurveP384"]

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = "cincenko@outlook.com"
      storage = "acme/certs.json"
      [certificatesResolvers.default.acme.dnsChallenge]
        provider = "ovh"
        delayBeforeCheck = "10s"
        resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = true
    swarmMode = false

[api]
  insecure = true
  dashboard = true
  debug = true

[log]
  level = "DEBUG"

