# Traefik version 2

[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[serversTransport]
  insecureSkipVerify = true
  maxIdleConnsPerHost = 0

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.traefik]
    address = ":9116"

[providers]
  providersThrottleDuration = "2s"
  [providers.docker]
    watch = true
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = true
    swarmMode = false

[api]
  insecure = true
  dashboard = true
  debug = true

[log]
  level = "INFO"

[certificatesResolvers]
  [certificatesResolvers.default]
    [certificatesResolvers.default.acme]
      email = "cincenko@outlook.com"
      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      storage = "acme/certs.json"
      [certificatesResolvers.default.acme.dnsChallenge]
        provider = "ovh"
        delayBeforeCheck = "10s"
