# Fetch secrets from "Library"
variables:
- group: VarGroup1

pool:
  vmImage: "windows-latest"

trigger:
  - docs

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- checkout: self
  persistCredentials: true

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: |
    git config --global user.email "cincenko@outlook.com"
    git config --global user.name "dmpe"
    pip3 install mkdocs mkdocs-material
    mkdocs --version
  displayName: Install PIP packages and print mkdocs version

- pwsh: |
    dir
    mkdocs build
    dir 
  displayName: Build site folder

- pwsh: |
    $ErrorActionPreference = "Continue" 
    cd $(Build.StagingDirectory)
    $var1 = $env:GitHubPAT
    git clone https://dmpe:$var1@github.com/dmpe/django-wohn.git .
    git checkout gh-pages
    Copy-Item -Path $(Build.SourcesDirectory)\site\* -Destination . -Recurse -Force -Verbose
    Write-Host "Done here"
  displayName: Clone site and overwrite files in git repo

- pwsh: |
    cd $(Build.StagingDirectory) 
    git checkout gh-pages
    git add --all
    git commit -a -m "Azure Pipeline MkDocs Build and Push - Build ID: $env:Build.BuildId "
    git push https://dmpe:$(GitHubPAT)@github.com/dmpe/django-wohn.git gh-pages
  displayName: Git Add & Commit and Push

