# Fetch secrets from "Library"
variables:
- group: VarGroup1

pool:
  vmImage: "ubuntu-latest"

trigger:
  - docs

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- checkout: self
  persistCredentials: true

- script: sudo apt-get update && sudo apt-get install -y tree locate 

- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- bash: |
    git config --global user.email "cincenko@outlook.com"
    git config --global user.name "dmpe"
    pip3 install mkdocs mkdocs-material
    mkdocs --version
  displayName: Install PIP packages and print mkdocs version

- bash: |
    mkdocs build
    ls 
    cp site/ $(Build.StagingDirectory)
    tree $(Build.StagingDirectory)
  displayName: Build site folder

# move site to other dir 

- bash: |
    cd $(Build.StagingDirectory)
    git clone --depth=1 https://github.com/dmpe/django-wohn.git .
    ls 
    git branch gh-pages
    cp $(Build.StagingDirectory)/site .
    git add .
    git commit -m "Azure Pipeline MkDocs Build and Push"
    git push https://$(GitHubPAT)@github.com/dmpe/django-wohn.git gh-pages