version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/error.log:/etc/nginx/error_log.log
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "54320:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    ports:
      - 80:80
      - 443:443


# https://hub.docker.com/r/dpage/pgadmin4/      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    env:
      - PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD
      PGADMIN_LISTEN_PORT
    ports:
      - 80:80
      - 443:443
    depends_on:
    - postgres

  rabbit:
    container_name: rabbit
    image: rabbitmq:latest
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin


web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - nginx
      - postgres
      - pgadmin
      - rabbit


volumes:
  my_dbdata: