version: '3.7'

# https://hub.docker.com/_/nginx
# https://tomlankhorst.nl/secure-nginx-docker-container-with-lets-encrypt/
# https://api.ovh.com/console/#/auth/credential#POST
services:
    traefik:
        image: traefik:2.1
        container_name: traefik
        ports:
          - "80:80"
          - "443:443"
        restart: always
        networks:
          - default
          - traefik_proxy
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./services/containers/traefik/traefik.toml:/traefik.toml
          - ./services/containers/traefik:/acme
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.monitor.rule=Host(`monitor.melive.xyz`, `www.monitor.melive.xyz`)"
          - "traefik.http.routers.monitor.service=api@internal"
          - "traefik.http.routers.monitorsec.tls.domains[0].main=melive.xyz"
          - "traefik.http.routers.monitorsec.tls.domains[0].sans=monitor.melive.xyz,pgadmin.melive.xyz"
          - "traefik.http.routers.monitorsec.tls=true"
          - "traefik.http.routers.monitorsec.rule=Host(`monitor.melive.xyz`, `www.monitor.melive.xyz`)"
          - "traefik.http.routers.monitorsec.tls.certresolver=default"
          - "traefik.http.routers.monitorsec.service=monitor"
          - "traefik.http.services.monitor.loadbalancer.server.port=8080"
          - "traefik.http.middlewares.monitor-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.monitor.middlewares=monitor-redirect"
          - "traefik.http.routers.monitor.entrypoints: web-secure"
        environment:
          - "OVH_ENDPOINT=ovh-eu"
          - "OVH_APPLICATION_KEY=w9tkF8kh3waFE01d"
          - "OVH_APPLICATION_SECRET=GIUVTjgdkAUCxK40sAtniEAeJc67GXP1"
          - "OVH_CONSUMER_KEY=Vo5S0YOYF5lO5HukxIOeqgbP6tKHV3OH"

    backend:
        image: quay.io/dmpe/django-wohn-backend
        container_name: backend
        volumes:
          - datadrive_django:/work
        restart: always
        ports:
          - 8123:8123
        depends_on:
          - postgres
          - pgadmin
          - traefik
        networks:
          - default
          - traefik_proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.backend.rule=Host(`melive.xyz`, `www.melive.xyz`) && (PathPrefix(`/admin`) || PathPrefix(`/graphql`))"
          - "traefik.http.routers.backendsec.tls=true"
          - "traefik.http.routers.backendsec.rule=Host(`melive.xyz`, `www.melive.xyz`) && (PathPrefix(`/admin`) || PathPrefix(`/graphql`))"
          - "traefik.http.routers.backendsec.tls.certresolver=default"
          - "traefik.http.routers.backendsec.service=backend"
          - "traefik.http.services.backend.loadbalancer.server.port=8123"
          - "traefik.http.middlewares.backend-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.backend.middlewares=backend-redirect"
          - "traefik.http.routers.backend.priority=1"
        environment:
          - "DOCKER_HOST=172.17.0.5"
          - "OVH_ENDPOINT=ovh-eu"
          - "OVH_APPLICATION_KEY=w9tkF8kh3waFE01d"
          - "OVH_APPLICATION_SECRET=GIUVTjgdkAUCxK40sAtniEAeJc67GXP1"
          - "OVH_CONSUMER_KEY=Vo5S0YOYF5lO5HukxIOeqgbP6tKHV3OH"

    frontend:
        image: quay.io/dmpe/django-wohn-frontend
        container_name: frontend
        restart: always
        ports:
          - 2746:2746
        depends_on:
          - postgres
          - pgadmin
          - traefik
        networks:
          - default
          - traefik_proxy
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.frontend.rule=Host(`melive.xyz`, `www.melive.xyz`)"
          - "traefik.http.routers.frontendsec.tls=true"
          - "traefik.http.routers.frontendsec.rule=Host(`melive.xyz`, `www.melive.xyz`)"
          - "traefik.http.routers.frontendsec.tls.certresolver=default"
          - "traefik.http.routers.frontendsec.service=frontend"
          - "traefik.http.services.frontend.loadbalancer.server.port=2746"
          - "traefik.http.middlewares.frontend-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.frontend.middlewares=frontend-redirect"
          - "traefik.http.routers.frontend.priority=2"
        volumes:
          - ./services/containers/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
        environment:
          - "OVH_ENDPOINT=ovh-eu"
          - "OVH_APPLICATION_KEY=w9tkF8kh3waFE01d"
          - "OVH_APPLICATION_SECRET=GIUVTjgdkAUCxK40sAtniEAeJc67GXP1"
          - "OVH_CONSUMER_KEY=Vo5S0YOYF5lO5HukxIOeqgbP6tKHV3OH"

# https://hub.docker.com/_/postgres
    postgres:
        image: postgres:12
        container_name: postgres
        volumes:
          - datadrive_postgress:/var/lib/postgresql/data
        restart: always
        ports:
          - 5432:5432
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=django
          - POSTGRES_DB=b40re
        labels:
          - "traefik.enable=false"
          - "traefik.http.services.postgres.loadbalancer.server.port=5432"

# https://hub.docker.com/r/dpage/pgadmin4/
    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        ports:
          - 3456:3456
        restart: always
        depends_on:
          - postgres
          - traefik
        networks:
          - default
        volumes:
          - datadrive_pgadmin:/var/lib/pgadmin
          - ./services/containers/pgadmin/config_local.py:/config_local.py
        labels:
          - "traefik.enable=true"
          - "traefik.http.services.pgadmin.loadbalancer.server.port=3456"
          - "traefik.http.routers.pgadminsec.rule=Host(`pgadmin.melive.xyz`, `www.pgadmin.melive.xyz`)"
          - "traefik.http.middlewares.pgadmin-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.pgadmin.middlewares=pgadmin-redirect"
          - "traefik.http.routers.pgadminsec.tls=true"
          - "traefik.http.routers.pgadminsec.tls.certresolver=default"
          - "traefik.http.routers.pgadminsec.service=pgadmin"
          - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.melive.xyz`, `www.pgadmin.melive.xyz`)"
        environment:
          - "OVH_ENDPOINT=ovh-eu"
          - "OVH_APPLICATION_KEY=w9tkF8kh3waFE01d"
          - "OVH_APPLICATION_SECRET=GIUVTjgdkAUCxK40sAtniEAeJc67GXP1"
          - "OVH_CONSUMER_KEY=Vo5S0YOYF5lO5HukxIOeqgbP6tKHV3OH"
          - PGADMIN_DEFAULT_EMAIL=cincenko@outlook.com
          - PGADMIN_DEFAULT_PASSWORD=123456
          - PGADMIN_LISTEN_PORT=3456

    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        restart: always
        networks:
          - default
        ports:
          - 7884:7884
        environment:
          - WATCHTOWER_CLEANUP=true
          - WATCHTOWER_NOTIFICATIONS=slack
        #   does not work because it needs to be secret
        #   - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=xxx
          - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=watchtower
          - WATCHTOWER_NOTIFICATIONS_LEVEL=debug
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ~/.docker/config.json:/config.json
        command: --interval 30
        labels:
          - "traefik.enable=false"
          - "traefik.http.services.watchtower.loadbalancer.server.port=7884"

    portainer:
        image: portainer/portainer:latest
        container_name: portainer
        restart: always
        ports:
          - "9000:9000"
          - "8000:8000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - datadrive_portainer:/data
        networks:
          - default
        labels:
          - "traefik.enable=true"
          - "traefik.http.services.portainer.loadbalancer.server.port=9000"
          - "traefik.http.routers.portainersec.rule=Host(`portainer.melive.xyz`, `www.portainer.melive.xyz`)"
          - "traefik.http.middlewares.portainer-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.portainer.middlewares=portainer-redirect"
          - "traefik.http.routers.portainersec.tls=true"
          - "traefik.http.routers.portainersec.tls.certresolver=default"
          - "traefik.http.routers.portainersec.service=portainer"
          - "traefik.http.routers.portainer.rule=Host(`portainer.melive.xyz`, `www.portainer.melive.xyz`)"
        environment:
          - "OVH_ENDPOINT=ovh-eu"
          - "OVH_APPLICATION_KEY=w9tkF8kh3waFE01d"
          - "OVH_APPLICATION_SECRET=GIUVTjgdkAUCxK40sAtniEAeJc67GXP1"
          - "OVH_CONSUMER_KEY=Vo5S0YOYF5lO5HukxIOeqgbP6tKHV3OH"
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

volumes:
  datadrive_postgress:
    external: true
  datadrive_portainer:
    external: true
  datadrive_pgadmin:
    external: true
  datadrive_django:
    external: true
