# Generated by Django 2.0.4 on 2018-04-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_rooms', models.IntegerField()),
                ('apartment_created', models.DateTimeField(auto_now_add=True)),
                ('apartment_price_eur', models.PositiveSmallIntegerField()),
                ('apartment_price_czk', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=200)),
                ('user_last_name', models.CharField(max_length=200)),
                ('user_created', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_int_tel', models.EmailField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='apartmenttype',
            name='apartment_offered_by',
            field=models.ManyToManyField(to='won.Users'),
        ),
    ]
