# Generated by Django 2.1 on 2018-08-31 15:11

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_rooms', models.IntegerField()),
                ('apartment_created', models.DateTimeField(auto_now_add=True)),
                ('apartment_price_eur', models.PositiveSmallIntegerField()),
                ('apartment_price_czk', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_created', models.DateTimeField(auto_now_add=True)),
                ('user_first_name', models.CharField(max_length=200)),
                ('user_last_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_int_tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='apartmenttype',
            name='apartment_offered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='won.User'),
        ),
    ]
