# Generated by Django 2.1 on 2018-08-31 13:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('won', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmenttype',
            name='apartment_offered_by',
        ),
        migrations.AddField(
            model_name='apartmenttype',
            name='apartment_offered_by',
            field=models.ForeignKey(default=datetime.datetime(2018, 8, 31, 13, 53, 55, 553556, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='won.Users'),
            preserve_default=False,
        ),
    ]
