# Generated by Django 2.1.3 on 2018-11-15 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment_rooms', models.IntegerField()),
                ('apartment_created', models.DateTimeField(auto_now_add=True)),
                ('apartment_price_eur', models.PositiveSmallIntegerField()),
                ('apartment_price_czk', models.PositiveIntegerField()),
                ('apartment_offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.DateField(auto_now_add=True, verbose_name="Today's Date")),
                ('OneEurCzk', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='1 EUR - CZK')),
                ('OneEurUsd', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='1 EUR - USD')),
                ('OneUsdCzk', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='1 USD - CZK')),
            ],
        ),
    ]
