# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
# https://circleci.com/gh/dmpe/django-wohn
version: 2.1
jobs:
  frontend_test:
    docker:
      - image: circleci/python:3-node
    working_directory: ~/repo
    steps:
      - checkout

      - run: |
          pwd
          ls -ls

      - run:
          name: Run Jest Tests
          command: |
            cd frontend/
            yarn run test

  build:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: ~/doc_repo
    steps:
      - checkout
      - run:
          name: Build and push Docker image
          command: |
            cd frontend/
            docker build -t quay.io/dmpe/django-wohn-frontend:latest .
            echo $DOCKER_PASS | docker login -u $DOCKER_LOGIN --password-stdin quay.io
            docker push quay.io/dmpe/django-wohn-frontend:latest

workflows:
  version: 2
  workflow:
    jobs:
    - frontend_test:
        filters:
          branches:
            ignore:
              - docs
              - server-config
              - gh-pages
              - azure-functions

    - build:
        context: DockerHub
        filters:
          branches:
            ignore:
              - docs
              - server-config
              - gh-pages
              - azure-functions
