defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8123"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:123"]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  # [entryPoints.https]
  #   address = ":443"
  #     [entryPoints.https.tls]

[api]
entrypoint="dashboard"
dashboard=true

# [acme]
# email = "your_email@your_domain"
# storage = "acme.json"
# entryPoint = "https"
# onHostRule = true
#   [acme.httpChallenge]
#   entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "melive.xyz"
watch = true
network = "traefik-proxy"