debug = true
logLevel = "INFO"
InsecureSkipVerify = true

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
			[entryPoints.http.redirect]
			entryPoint = "https"

    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
      ]

    [entryPoints.traefik]
    address = ":9116"
    #  [entryPoints.traefik.auth]
    #    [entryPoints.traefik.auth.basic]
    #    users = ["admin:$$2y$$05$$rwTXazYt3S4Yp3cUWRpZdO7DQX5WckETjbROy2vOAg9PedrhsCuIe"]

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
# [file]
# watch = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "melive.xyz"
watch = true
exposedByDefault = true
# network = "traefik-proxy"

[acme]
email = "cincenko@outlook.com"
storage = "acme/certs.json"
entryPoint = "https"
resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
#caServer = "https://acme-v02.api.letsencrypt.org/directory"
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
onHostRule = true
  [acme.dnsChallenge]
  provider = "ovh"
  delayBeforeCheck = 10

[[acme.domains]]
  main = "*.melive.xyz"
	sans = ["melive.xyz", "pgadmin.melive.xyz", "portainer.melive.xyz"]
