debug = true
logLevel = "INFO"
InsecureSkipVerify = true

[global]
  # Send anonymous usage data
  sendAnonymousUsage = true

# defaultEntryPoints = ["http", "https"]

# [entryPoints]
#   [entryPoints.dashboard]
#     address = ":9115"
#     [entryPoints.dashboard.auth]
#       [entryPoints.dashboard.auth.basic]
#         users = ["admin:$$apr1$$IBa8vpEo$$T7M3PWdYfMIkQhn2MAI6n1"]
#   [entryPoints.http]
#     address = ":80"
      # [entryPoints.http.redirect]
      #   entryPoint = "https"
  # [entryPoints.https]
  #   address = ":443"
  #     [entryPoints.https.tls]

[api]
dashboard=true
debug=true

# [certificatesResolvers.myhttpchallenge.acme]
# email = "cincenko@outlook.com"
# storage = "acme.json"
# entryPoint = "https"
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
# onHostRule = true
#   [certificatesResolvers.myhttpchallenge.acme.dnsChallenge]
#   resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
#   provider = "ovh"
#   delayBeforeCheck = 10

# [[acme.domains]]
#   main = "*.melive.xyz"
#   sans = ["melive.xyz"]

# [[acme.domains]]
#    main = "melive.xyz"

[certificatesResolvers]
  [certificatesResolvers.myhttpchallenge]
    [certificatesResolvers.myhttpchallenge.acme]
      email = "cincenko@outlook.com"
      caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      storage = "acme.json"
      [certificatesResolvers.myhttpchallenge.acme.dnsChallenge]
        provider = "ovh"
        delayBeforeCheck = 10
        resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

[providers.docker]
# endpoint = "unix:///var/run/docker.sock"
  # domain = "melive.xyz"
  # watch = true
  exposedByDefault = true