debug = false
logLevel = "ERROR"

[api]
  entryPoint = "dashboard"
  dashboard = true

defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
#        [entryPoints.http.redirect]
#        entryPoint = "https"

    [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
	 #    minVersion = "VersionTLS12"
   #    cipherSuites = [
   #      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
   #      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
   #      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
   #      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
   #    ]

		[entryPoints.dashboard]
		address = ":8080"
		[entryPoints.dashboard.auth]
		  [entryPoints.dashboard.auth.basic]
		    users = ["admin:$apr1$ciQGGpnM$qQuteuC8B.h6P.k3zl05P0"]

[retry]

[file]
watch = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "melive.xyz"
watch = true
exposedByDefault = true
network = "web"

[acme]
email = "cincenko@outlook.com"
storage = "acme.json"
entryPoint = "https"
KeyType = "EC384"
resolvers = ["1.1.1.1:53", "8.8.8.8:53"]
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
onHostRule = true
    [acme.dnsChallenge]
    provider = "ovh"
    delayBeforeCheck = 0

[[acme.domains]]
  main = "*.melive.xyz"
