# Generated by Django 2.1.3 on 2018-11-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userMng', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together={('email', 'username')},
        ),
    ]
