# Generated by Django 2.1.7 on 2019-03-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userMng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='from_whom',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='to_whom',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
