# Generated by Django 2.2.6 on 2019-11-02 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191102_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='apartment_floor',
            new_name='room_floor',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_address_zipcode',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(9999), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_address_zipcode',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(9999), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='room',
            name='property_address_zipcode',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(9999), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
