# Generated by Django 2.2.6 on 2019-11-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191102_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_floor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_status',
            field=models.CharField(choices=[('N', 'New'), ('G', 'Good'), ('UC', 'Under Construction')], default='G', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_wash_machine',
            field=models.CharField(choices=[('O', 'Owned'), ('S', 'Shared in house'), ('NP', 'Not present')], default='NP', max_length=3),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_status',
            field=models.CharField(choices=[('N', 'New'), ('G', 'Good'), ('UC', 'Under Construction')], default='G', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_wash_machine',
            field=models.CharField(choices=[('O', 'Owned'), ('S', 'Shared in house'), ('NP', 'Not present')], default='NP', max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='property_status',
            field=models.CharField(choices=[('N', 'New'), ('G', 'Good'), ('UC', 'Under Construction')], default='G', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='property_wash_machine',
            field=models.CharField(choices=[('O', 'Owned'), ('S', 'Shared in house'), ('NP', 'Not present')], default='NP', max_length=3),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_floor',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
